/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ProfessionnelsRouteImport } from './routes/professionnels'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as ParticuliersRouteImport } from './routes/particuliers'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPlacoPlatrerieRouteImport } from './routes/services/placo-platrerie'
import { Route as ServicesPeintureInterieureRouteImport } from './routes/services/peinture-interieure'
import { Route as ServicesPeintureExterieureRouteImport } from './routes/services/peinture-exterieure'
import { Route as ServicesInstallationCuisineRouteImport } from './routes/services/installation-cuisine'
import { Route as ServicesDecorationInterieureRouteImport } from './routes/services/decoration-interieure'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionnelsRoute = ProfessionnelsRouteImport.update({
  id: '/professionnels',
  path: '/professionnels',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParticuliersRoute = ParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlacoPlatrerieRoute = ServicesPlacoPlatrerieRouteImport.update({
  id: '/placo-platrerie',
  path: '/placo-platrerie',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPeintureInterieureRoute =
  ServicesPeintureInterieureRouteImport.update({
    id: '/peinture-interieure',
    path: '/peinture-interieure',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPeintureExterieureRoute =
  ServicesPeintureExterieureRouteImport.update({
    id: '/peinture-exterieure',
    path: '/peinture-exterieure',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInstallationCuisineRoute =
  ServicesInstallationCuisineRouteImport.update({
    id: '/installation-cuisine',
    path: '/installation-cuisine',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDecorationInterieureRoute =
  ServicesDecorationInterieureRouteImport.update({
    id: '/decoration-interieure',
    path: '/decoration-interieure',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/decoration-interieure': typeof ServicesDecorationInterieureRoute
  '/services/installation-cuisine': typeof ServicesInstallationCuisineRoute
  '/services/peinture-exterieure': typeof ServicesPeintureExterieureRoute
  '/services/peinture-interieure': typeof ServicesPeintureInterieureRoute
  '/services/placo-platrerie': typeof ServicesPlacoPlatrerieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/decoration-interieure': typeof ServicesDecorationInterieureRoute
  '/services/installation-cuisine': typeof ServicesInstallationCuisineRoute
  '/services/peinture-exterieure': typeof ServicesPeintureExterieureRoute
  '/services/peinture-interieure': typeof ServicesPeintureInterieureRoute
  '/services/placo-platrerie': typeof ServicesPlacoPlatrerieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/decoration-interieure': typeof ServicesDecorationInterieureRoute
  '/services/installation-cuisine': typeof ServicesInstallationCuisineRoute
  '/services/peinture-exterieure': typeof ServicesPeintureExterieureRoute
  '/services/peinture-interieure': typeof ServicesPeintureInterieureRoute
  '/services/placo-platrerie': typeof ServicesPlacoPlatrerieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/particuliers'
    | '/politique-confidentialite'
    | '/professionnels'
    | '/realisations'
    | '/services'
    | '/services/decoration-interieure'
    | '/services/installation-cuisine'
    | '/services/peinture-exterieure'
    | '/services/peinture-interieure'
    | '/services/placo-platrerie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/particuliers'
    | '/politique-confidentialite'
    | '/professionnels'
    | '/realisations'
    | '/services'
    | '/services/decoration-interieure'
    | '/services/installation-cuisine'
    | '/services/peinture-exterieure'
    | '/services/peinture-interieure'
    | '/services/placo-platrerie'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/particuliers'
    | '/politique-confidentialite'
    | '/professionnels'
    | '/realisations'
    | '/services'
    | '/services/decoration-interieure'
    | '/services/installation-cuisine'
    | '/services/peinture-exterieure'
    | '/services/peinture-interieure'
    | '/services/placo-platrerie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ParticuliersRoute: typeof ParticuliersRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ProfessionnelsRoute: typeof ProfessionnelsRoute
  RealisationsRoute: typeof RealisationsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionnels': {
      id: '/professionnels'
      path: '/professionnels'
      fullPath: '/professionnels'
      preLoaderRoute: typeof ProfessionnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particuliers': {
      id: '/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof ParticuliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/placo-platrerie': {
      id: '/services/placo-platrerie'
      path: '/placo-platrerie'
      fullPath: '/services/placo-platrerie'
      preLoaderRoute: typeof ServicesPlacoPlatrerieRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/peinture-interieure': {
      id: '/services/peinture-interieure'
      path: '/peinture-interieure'
      fullPath: '/services/peinture-interieure'
      preLoaderRoute: typeof ServicesPeintureInterieureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/peinture-exterieure': {
      id: '/services/peinture-exterieure'
      path: '/peinture-exterieure'
      fullPath: '/services/peinture-exterieure'
      preLoaderRoute: typeof ServicesPeintureExterieureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/installation-cuisine': {
      id: '/services/installation-cuisine'
      path: '/installation-cuisine'
      fullPath: '/services/installation-cuisine'
      preLoaderRoute: typeof ServicesInstallationCuisineRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/decoration-interieure': {
      id: '/services/decoration-interieure'
      path: '/decoration-interieure'
      fullPath: '/services/decoration-interieure'
      preLoaderRoute: typeof ServicesDecorationInterieureRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesDecorationInterieureRoute: typeof ServicesDecorationInterieureRoute
  ServicesInstallationCuisineRoute: typeof ServicesInstallationCuisineRoute
  ServicesPeintureExterieureRoute: typeof ServicesPeintureExterieureRoute
  ServicesPeintureInterieureRoute: typeof ServicesPeintureInterieureRoute
  ServicesPlacoPlatrerieRoute: typeof ServicesPlacoPlatrerieRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDecorationInterieureRoute: ServicesDecorationInterieureRoute,
  ServicesInstallationCuisineRoute: ServicesInstallationCuisineRoute,
  ServicesPeintureExterieureRoute: ServicesPeintureExterieureRoute,
  ServicesPeintureInterieureRoute: ServicesPeintureInterieureRoute,
  ServicesPlacoPlatrerieRoute: ServicesPlacoPlatrerieRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ParticuliersRoute: ParticuliersRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ProfessionnelsRoute: ProfessionnelsRoute,
  RealisationsRoute: RealisationsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
